# Generated by Django 4.2.20 on 2025-04-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofcoremodel',
            name='core_manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='typeofharddiskmodel',
            name='disk_memory_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер памяти диска'),
        ),
        migrations.AlterField(
            model_name='typeoframmodel',
            name='ram_memory_standard',
            field=models.CharField(blank=True, help_text='DDR4/DDR5', max_length=10, null=True, verbose_name='Стандарт памяти RAM'),
        ),
    ]
