# Generated by Django 4.2.20 on 2025-04-23 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_app', '0002_alter_typeofcoremodel_core_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='equipment_serial_number',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.CreateModel(
            name='EquipmentEmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=10, null=True, verbose_name='кабинет')),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_app.employeemodel', verbose_name='Сотрудник')),
                ('equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_app.equipmentmodel', verbose_name='Оборудование/техника')),
            ],
            options={
                'verbose_name': 'оборудование у сотрудника',
                'verbose_name_plural': 'оборудование у сотрудников',
            },
        ),
    ]
